export default function Overview({data}){
const packets=data?.packets||{};
const latency=data?.latency||{};
const security=data?.security||{};
const queue=data?.queue||{};
const failures=data?.failures||{};
const traffic=data?.traffic||[];
const nodes=data?.nodes||[];
const links=data?.links||[];
const alerts=data?.alerts||[];
const total=Number(packets.total||0);
const delivered=Number(packets.delivered||0);
const dropped=Number(packets.dropped||0);
const deliveryRate=total?((delivered/total)*100).toFixed(1):"0.0";
const lossRate=total?((dropped/total)*100).toFixed(1):"0.0";
const health=data?.health||"NO TRAFFIC";
const healthClass=health==="HEALTHY"?"overview-good":health==="WARNING"?"overview-warning":health==="DEGRADED"?"overview-danger":health==="CRITICAL"?"overview-critical":"overview-neutral";

return <section className="overview-page">
<div className="overview-hero">
<div>
<span className="section-label">NETSIMX CONTROL CENTER</span>
<h1>Network Overview</h1>
<p>Unified view of topology, traffic, security and network performance.</p>
</div>
<div className={`overview-health ${healthClass}`}>
<span></span>
<div>
<small>NETWORK HEALTH</small>
<strong>{health}</strong>
</div>
</div>
</div>

<div className="overview-stats">
<div className="overview-stat">
<span>Total Packets</span>
<strong>{total}</strong>
<small>Generated by simulation</small>
</div>
<div className="overview-stat">
<span>Delivery Rate</span>
<strong>{deliveryRate}%</strong>
<small>{delivered} packets delivered</small>
</div>
<div className="overview-stat">
<span>Throughput</span>
<strong>{Number(latency.throughput||0).toFixed(2)}</strong>
<small>Mbps</small>
</div>
<div className="overview-stat">
<span>Average Latency</span>
<strong>{Number(latency.average||0).toFixed(2)}</strong>
<small>milliseconds</small>
</div>
</div>

<div className="overview-grid">
<div className="overview-card traffic-overview-card">
<div className="overview-card-heading">
<div>
<h3>Traffic Overview</h3>
<p>Protocol activity in the latest simulation.</p>
</div>
<span>{traffic.length} Protocols</span>
</div>
<div className="overview-traffic-list">
{traffic.map(item=>{
const packetsCount=Number(item.packets||0);
const deliveredCount=Number(item.delivered||0);
const percentage=total?Math.min((packetsCount/total)*100,100):0;
return <div className="overview-traffic-row" key={item.protocol}>
<div className="overview-traffic-title">
<strong>{item.protocol}</strong>
<span>{packetsCount} packets</span>
</div>
<div className="overview-progress"><div style={{width:`${percentage}%`}}></div></div>
<div className="overview-traffic-value">{deliveredCount}/{packetsCount}</div>
</div>;
})}
{traffic.length===0&&<div className="overview-empty">No traffic data available.</div>}
</div>
</div>

<div className="overview-card security-overview-card">
<div className="overview-card-heading">
<div>
<h3>Security Status</h3>
<p>Firewall and IDS activity.</p>
</div>
</div>
<div className="overview-security-main">
<div className={`security-ring ${Number(security.critical||0)>0?"ring-danger":Number(security.high||0)>0?"ring-warning":"ring-safe"}`}>
<strong>{security.idsAlerts||0}</strong>
<span>IDS Alerts</span>
</div>
<div className="overview-security-list">
<div><span>Allowed</span><strong>{security.firewallAllowed||0}</strong></div>
<div><span>Denied</span><strong>{security.firewallDenied||0}</strong></div>
<div><span>Critical</span><strong>{security.critical||0}</strong></div>
<div><span>High</span><strong>{security.high||0}</strong></div>
</div>
</div>
</div>
</div>

<div className="overview-grid">
<div className="overview-card">
<div className="overview-card-heading">
<div>
<h3>Performance</h3>
<p>Current network performance indicators.</p>
</div>
</div>
<div className="overview-performance">
<div className="performance-item">
<span>Packet Loss</span>
<strong>{lossRate}%</strong>
<div className="mini-progress"><div style={{width:`${Math.min(Number(lossRate),100)}%`}}></div></div>
</div>
<div className="performance-item">
<span>Queue Utilization</span>
<strong>{Number(queue.utilization||0).toFixed(1)}%</strong>
<div className="mini-progress"><div style={{width:`${Math.min(Number(queue.utilization||0),100)}%`}}></div></div>
</div>
<div className="performance-item">
<span>Queue Drops</span>
<strong>{queue.drops||0}</strong>
</div>
<div className="performance-item">
<span>Queue Delay</span>
<strong>{Number(queue.averageDelay||0).toFixed(2)} ms</strong>
</div>
</div>
</div>

<div className="overview-card">
<div className="overview-card-heading">
<div>
<h3>Network Reliability</h3>
<p>Failure and recovery activity.</p>
</div>
</div>
<div className="reliability-content">
<div className="reliability-number">
<strong>{failures.linkFailures||0}</strong>
<span>Link Failures</span>
</div>
<div className="reliability-arrow">↔</div>
<div className="reliability-number">
<strong>{failures.recoveries||0}</strong>
<span>Recoveries</span>
</div>
</div>
<div className="reliability-footer">
<span>Active Links</span>
<strong>{links.filter(link=>link.status==="ACTIVE").length}/{links.length}</strong>
</div>
</div>
</div>

<div className="overview-card topology-overview">
<div className="overview-card-heading">
<div>
<h3>Network Topology</h3>
<p>Current simulated network infrastructure.</p>
</div>
</div>
<div className="topology-summary">
<div><strong>{nodes.length}</strong><span>Nodes</span></div>
<div><strong>{links.length}</strong><span>Total Links</span></div>
<div><strong>{links.filter(link=>link.status==="ACTIVE").length}</strong><span>Active Links</span></div>
<div><strong>{alerts.length}</strong><span>Security Events</span></div>
</div>
<div className="topology-mini">
{nodes.map(node=><div className="topology-node" key={node.id}>
<span className={`node-icon ${String(node.type||"").toLowerCase()}`}>{node.type==="ROUTER"?"R":"H"}</span>
<div><strong>{node.name}</strong><small>{node.ip}</small></div>
</div>)}
</div>
</div>

<div className="overview-footer">
<div>
<span>NetSimX Simulation Engine</span>
<strong>Phase 22 — Advanced Visualization</strong>
</div>
<div>
<span>Nodes</span><strong>{nodes.length}</strong>
<span>Links</span><strong>{links.length}</strong>
<span>Alerts</span><strong>{alerts.length}</strong>
</div>
</div>
</section>;
}