import{BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend}from"recharts";

export default function Traffic({data}){
const traffic=data?.traffic||[];
const total=traffic.reduce((sum,item)=>sum+Number(item.packets||0),0);
const delivered=traffic.reduce((sum,item)=>sum+Number(item.delivered||0),0);
const dropped=traffic.reduce((sum,item)=>sum+Number(item.dropped||0),0);

return <section className="traffic-page">
<div className="page-heading">
<div>
<span className="section-label">NETWORK TRAFFIC</span>
<h2>Traffic Analysis</h2>
<p>Protocol-level traffic generated by the NetSimX simulation engine.</p>
</div>
<div className="traffic-total">
<strong>{total}</strong>
<span>Total Packets</span>
</div>
</div>

<div className="traffic-summary">
<div className="traffic-stat">
<span>Total Packets</span>
<strong>{total}</strong>
</div>
<div className="traffic-stat">
<span>Delivered</span>
<strong>{delivered}</strong>
</div>
<div className="traffic-stat">
<span>Dropped</span>
<strong>{dropped}</strong>
</div>
<div className="traffic-stat">
<span>Delivery Rate</span>
<strong>{total?((delivered/total)*100).toFixed(1):"0.0"}%</strong>
</div>
</div>

<div className="traffic-chart-card">
<div className="card-heading">
<div>
<h3>Protocol Traffic</h3>
<p>Packets generated, delivered and dropped by protocol.</p>
</div>
</div>
<div className="traffic-chart">
<ResponsiveContainer width="100%" height={340}>
<BarChart data={traffic}>
<CartesianGrid strokeDasharray="3 3"/>
<XAxis dataKey="protocol"/>
<YAxis allowDecimals={false}/>
<Tooltip/>
<Legend/>
<Bar dataKey="packets" name="Packets"/>
<Bar dataKey="delivered" name="Delivered"/>
<Bar dataKey="dropped" name="Dropped"/>
</BarChart>
</ResponsiveContainer>
</div>
</div>

<div className="traffic-table-card">
<div className="card-heading">
<h3>Protocol Statistics</h3>
</div>
<div className="table-wrapper">
<table>
<thead>
<tr>
<th>Protocol</th>
<th>Packets</th>
<th>Delivered</th>
<th>Dropped</th>
<th>Delivery Rate</th>
</tr>
</thead>
<tbody>
{traffic.map(item=>{
const packets=Number(item.packets||0);
const deliveredCount=Number(item.delivered||0);
return <tr key={item.protocol}>
<td><strong>{item.protocol}</strong></td>
<td>{packets}</td>
<td>{deliveredCount}</td>
<td>{Number(item.dropped||0)}</td>
<td>{packets?((deliveredCount/packets)*100).toFixed(1):"0.0"}%</td>
</tr>;
})}
</tbody>
</table>
</div>
</div>
</section>;
}